# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fecrt_sim_paired_LP <- function(iters, red, N, mu, cv_pre, cv_post, ncor, thresholds, conjugate_priors, delta, beta_iters, approx, tail, useml, dobson_cl, dobson_priors) {
    .Call('_bayescount_fecrt_sim_paired_LP', PACKAGE = 'bayescount', iters, red, N, mu, cv_pre, cv_post, ncor, thresholds, conjugate_priors, delta, beta_iters, approx, tail, useml, dobson_cl, dobson_priors)
}

